# Generated by Django 4.2.6 on 2023-10-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_collection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="user<built-in function id>", max_length=255
            ),
        ),
    ]
