# Generated by Django 4.2.6 on 2023-10-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "data_collection",
            "0003_remove_user_id_alter_user_ip_alter_user_national_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image1",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="image2",
            field=models.ImageField(upload_to=""),
        ),
    ]
