# Generated by Django 4.2.6 on 2023-10-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_collection", "0006_alter_user_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
