# Generated by Django 4.2.6 on 2023-10-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_collection", "0007_alter_user_national_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
            ],
        ),
    ]
