# Generated by Django 4.2.6 on 2023-10-25 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_collection", "0008_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
